### ISSUE TITLE
コミット結果の反映

### ISSUE THREAD

**Issue by kmuto** [reviewml/reviewml.org#2]
reviewml.orgへの反映ってgh-pagesにpushしたあと何かするんでしたっけ。

**Comment by takahashim** [comment]
ああっと、readmeじゃなくてindex.htmlを修正する必要があります。
ja/index.html はすでに反映されているようです。 http://reviewml.org/ja/

**Comment by kmuto** [comment]
あ、しまった、そういうことですね。直します
